{
 "title": "added",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Business KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg LLM Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "rate(chat2carpool_llm_duration_seconds_sum[1m]) / rate(chat2carpool_llm_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Matches",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chat2carpool_matches_found_total[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (Req / Sec)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chat2carpool_intent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User  Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Request VS Offer Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 1, "y": 16 },
   "targets": [
    {
     "expr": "sum by (intent_type) (rate(chat2carpool_intent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Intent Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (intent_type) (increase(chat2carpool_intent_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Health & Debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 1, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chat2carpool_app_errors_total[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"chat2carpool_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(chat2carpool_db_ops_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}